### ISSUE TITLE
Computing covariance matrix

### ISSUE THREAD

**Issue by NicolasDurrande** [goldingn/gpflowr#8]
Hi again

I am experimenting issues with covariance matrix computation. In some tests, I have used `tf$Session()$run(kernel$K(X))` which works just fine, but there are "helpers" that are more user oriented that do not work for now:

```
library(gpflowr)

# just fine
X <- matrix(runif(10),10,1)
X2 <- matrix(runif(12),12,1)
k <- kernels$RBF(1)

#errors
K <- k$compute_K(X,X2)
K <- k$compute_K_symm(X)
Kdiag <- k$compute_Kdiag(X)
```
the output for the first two errors is
```
Error in eval(substitute(expr), envir, enclos) : 
  ValueError: as_list() is not defined on an unknown TensorShape.
```
and for the last one, error says that `k$compute_Kdiag` is not a function.

Any thoughts?

**Comment by goldingn** [comment]
Hi N,
Yup, I didn't manage to get autoflow (the clever bit that overwrites functions to run via tensorflow, caching data) working yet. That's my focus for this morning, will let you know how I get on!

**Comment by goldingn** [comment]
This took a bit longer than I'd hoped, but autoflow is now working on master, and I registered the autoflowed Kdiag method. I get the following on a modified version of the MWE:

```r
library(gpflowr)
X <- matrix(runif(3), ncol = 1)
X2 <- matrix(runif(4), ncol = 1)
k <- kernels$RBF(1)

k$compute_K_symm(X)
```
```
          [,1]      [,2]      [,3]
[1,] 1.0000000 0.9914959 0.9611905
[2,] 0.9914959 1.0000000 0.9186081
[3,] 0.9611905 0.9186081 1.0000000
```
```r
k$compute_K(X, X2)
```
```
          [,1]      [,2]      [,3]      [,4]
[1,] 0.9046513 0.9214427 0.9132653 0.8589681
[2,] 0.8459843 0.9632060 0.8564646 0.9153044
[3,] 0.9862657 0.7904032 0.9895977 0.7069812
```
```r
k$compute_Kdiag(X)
```
```
[1] 1 1 1
```

**Comment by goldingn** [comment]
nullified by #27
